name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        brew install boost
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=clang++ ..
    - name: Compile
      run: |
        cd build
        cmake --build .
        ./hello

  linux:
    runs-on: ubuntu-latest
    env:
      BOOST_ROOT: dummy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Print environment variables
      run: |
        echo $BOOST_ROOT
        echo $BOOST_ROOT_1_72_0
        echo $BOOST_ROOT_1_69_0
        ls $BOOST_ROOT_1_72_0
    - name: cmake
      env:
        BOOST_ROOT: ${BOOST_ROOT_1_72_0}
        CXXFLAGS: -Werror -Wall -Wextra
      run: |
        export BOOST_ROOT=$BOOST_ROOT_1_72_0
        export 
        echo $BOOST_ROOT
        mkdir build
        cd build
        cmake ..
        VERBOSE=1 cmake --build .
        export PATH=${PATH}:${BOOST_ROOT}
        ./hello
