name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      BOOST_ROOT: $BOOST_ROOT_1_72_0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Print environment variables
      run: |
        echo $BOOST_ROOT
        echo $BOOST_ROOT_1_72_0
        echo $BOOST_ROOT_1_69_0
        ls $BOOST_ROOT_1_72_0
    - name: cmake
      env:
        BOOST_ROOT:  $BOOST_ROOT
      run: |
        mkdir build
        cd build
        cmake ..
        
