name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Print environment variables
      run: |
        echo $BOOST_ROOT
        echo $BOOST_ROOT_1_72_0
        echo $BOOST_ROOT_1_69_0
